import { createFileRoute } from "@tanstack/react-router";
import { Activity, ArrowDownRight, ArrowUpRight } from "lucide-react";
import { AppShell, Breadcrumb, PageHeading } from "@/components/layout/app-shell";
import { TrendChart } from "@/components/dashboard/trend-chart";
import { MetricCard } from "@/components/shared/metric-card";
import { ZoneTable } from "@/components/shared/zone-table";
import { zones } from "@/data/mock-data";

export const Route = createFileRoute("/crop-health")({ head: () => ({ meta: [{ title: "Crop health — Ceres Intelligence" }, { name: "description", content: "Understand crop health trends and identify declining zones." }, { property: "og:title", content: "Crop health — Ceres Intelligence" }, { property: "og:description", content: "Understand crop health trends and identify declining zones." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CropHealthPage });

function CropHealthPage() { const attention = zones.filter((zone) => zone.status !== "healthy"); return <AppShell title="Crop health"><Breadcrumb label="Crop health" /><PageHeading title="Crop health" description="Track the health signal over time and focus attention where field conditions are declining." /><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><MetricCard label="Overall score" value="84%" note="Across all zones" icon={Activity} tone="healthy" /><MetricCard label="7-day movement" value="+2.4%" note="Compared with prior week" icon={ArrowUpRight} tone="healthy" /><MetricCard label="Zones declining" value="03" note="Requires review" icon={ArrowDownRight} tone="attention" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(300px,0.75fr)]"><section className="panel rounded-lg p-5"><div className="mb-5"><h3 className="font-medium">Health trend</h3><p className="mt-1 text-xs text-muted-foreground">Cumulative health index · last 30 days</p></div><TrendChart /></section><section className="panel rounded-lg p-5"><h3 className="font-medium">Health distribution</h3><p className="mt-1 text-xs text-muted-foreground">Current status across 12 monitored zones</p><div className="mt-8 space-y-5"><HealthBar label="Healthy" count={9} total={12} color="bg-primary" /><HealthBar label="Moderate" count={2} total={12} color="bg-chart-2" /><HealthBar label="High stress" count={1} total={12} color="bg-destructive" /></div><div className="mt-8 border-t border-border pt-4 text-xs text-muted-foreground">Most recent change: Z08 declined 14% over the last 48 hours.</div></section></div><section className="panel mt-6 overflow-hidden rounded-lg"><div className="border-b border-border px-5 py-4"><h3 className="font-medium">Zones requiring attention</h3><p className="mt-1 text-xs text-muted-foreground">Prioritized by health score and recent movement.</p></div><ZoneTable zones={attention} /></section></AppShell>; }
function HealthBar({ label, count, total, color }: { label: string; count: number; total: number; color: string }) { return <div><div className="mb-2 flex justify-between text-xs"><span>{label}</span><span className="font-medium">{count} zones</span></div><div className="h-2 rounded-full bg-muted"><div className={`h-full rounded-full ${color}`} style={{ width: `${(count / total) * 100}%` }} /></div></div>; }