import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowLeft, CalendarDays } from "lucide-react";
import { AppShell, Breadcrumb, PageHeading } from "@/components/layout/app-shell";
import { FarmZoneMap } from "@/components/dashboard/farm-zone-map";
import { ZoneDetailPanel } from "@/components/shared/zone-detail-panel";
import { ZoneTable } from "@/components/shared/zone-table";
import { farms, getZone, primaryFarm, zones } from "@/data/mock-data";
import { useState } from "react";

export const Route = createFileRoute("/farms/$farmId")({ head: () => ({ meta: [{ title: "Farm analysis — Ceres Intelligence" }, { name: "description", content: "Inspect zone-level crop health and irrigation conditions." }, { property: "og:title", content: "Farm analysis — Ceres Intelligence" }, { property: "og:description", content: "Inspect zone-level crop health and irrigation conditions." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: FarmAnalysisPage });

function FarmAnalysisPage() { const { farmId } = Route.useParams(); const farm = farms.find((item) => item.id === farmId) ?? primaryFarm; const [selectedId, setSelectedId] = useState(farm.zoneIds[0] ?? "Z08"); const selected = getZone(selectedId); return <AppShell title="Farm analysis" eyebrow={farm.name}><Breadcrumb label="Farm analysis" /><PageHeading title={farm.name} description={`${farm.cropType} · ${farm.location}`} action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-4" />Analyzed {farm.lastAnalysis}</div>} /><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-3"><span className="text-sm text-muted-foreground">Overall health</span><span className="text-2xl font-medium text-primary">{farm.overallHealth}%</span></div><Link to="/farms" className="flex items-center gap-2 text-xs font-medium text-primary hover:underline"><ArrowLeft className="size-3.5" />Back to farms</Link></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.7fr)_minmax(280px,0.8fr)]"><FarmZoneMap onSelect={(zone) => setSelectedId(zone.id)} /><ZoneDetailPanel zone={selected} /></div><section className="panel mt-6 overflow-hidden rounded-lg"><div className="border-b border-border px-5 py-4"><h3 className="font-medium">Zone analysis</h3><p className="mt-1 text-xs text-muted-foreground">Detailed measurements for the {farm.name} field network.</p></div><ZoneTable zones={zones.filter((zone) => farm.zoneIds.includes(zone.id))} /></section></AppShell>; }