import { createFileRoute } from "@tanstack/react-router";
import { Check, Droplets, Gauge } from "lucide-react";
import { useState } from "react";
import { AppShell, Breadcrumb, PageHeading } from "@/components/layout/app-shell";
import { RecommendationCard } from "@/components/dashboard/recommendation-card";
import { PriorityBadge } from "@/components/shared/status";
import { recommendations } from "@/data/mock-data";
import type { Recommendation } from "@/types/agriculture";

export const Route = createFileRoute("/irrigation")({ head: () => ({ meta: [{ title: "Irrigation — Ceres Intelligence" }, { name: "description", content: "Review explainable irrigation recommendations ranked by operational priority." }, { property: "og:title", content: "Irrigation — Ceres Intelligence" }, { property: "og:description", content: "Review explainable irrigation recommendations ranked by operational priority." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: IrrigationPage });

function IrrigationPage() { const [completed, setCompleted] = useState<string[]>([]); const high = recommendations.filter((item) => item.priority === "high"); const medium = recommendations.filter((item) => item.priority === "medium"); const finish = (item: Recommendation) => setCompleted((current) => current.includes(item.id) ? current : [...current, item.id]); return <AppShell title="Irrigation"><Breadcrumb label="Irrigation" /><PageHeading title="Irrigation recommendations" description="Ranked actions based on moisture, vegetation health, and recent field conditions." action={<div className="flex items-center gap-2 rounded-md bg-primary/10 px-3 py-2 text-xs text-primary"><Gauge className="size-4" />12 zones assessed</div>} /><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(300px,0.75fr)]"><section className="panel rounded-lg p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-medium">Recommended actions</h3><p className="mt-1 text-xs text-muted-foreground">The next best actions for this field network.</p></div><Droplets className="size-4 text-primary" /></div>{[...high, ...medium].map((item) => <div key={item.id} className={completed.includes(item.id) ? "opacity-50" : ""}><RecommendationCard recommendation={item} onAction={() => finish(item)} />{completed.includes(item.id) ? <p className="-mt-3 mb-4 flex items-center gap-2 text-xs text-primary"><Check className="size-3.5" />Added to irrigation cycle</p> : null}</div>)}</section><div className="space-y-6"><section className="panel rounded-lg p-5"><h3 className="font-medium">Priority overview</h3><div className="mt-5 space-y-4"><PriorityRow label="High priority" value="1 zone" priority="high" /><PriorityRow label="Medium priority" value="2 zones" priority="medium" /><PriorityRow label="Low priority" value="9 zones" priority="low" /></div></section><section className="panel rounded-lg p-5"><h3 className="font-medium">Decision basis</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Recommendations combine soil moisture, NDVI movement, water stress, and the previous irrigation cycle. Each action is explainable and can be reviewed before scheduling.</p></section></div></div></AppShell>; }
function PriorityRow({ label, value, priority }: { label: string; value: string; priority: "high" | "medium" | "low" }) { return <div className="flex items-center justify-between border-b border-border pb-3 last:border-0 last:pb-0"><PriorityBadge priority={priority} /><span className="text-sm text-muted-foreground">{value}</span></div>; }